project:
  type: book

execute:
  freeze: auto

lang: pt
book:
  title: "Introdução à acessibilidade urbana"
  subtitle: "um guia prático em R"
  date: today
  status: "advance online publication"
  type: "book"
  language: pt
  cover-image: images/cover.png
  site-url: https://ipeagit.github.io/intro_access_book/pt
  repo-url: https://github.com/ipeaGIT/intro_access_book 
  repo-branch: main
  repo-actions: [edit]
  sharing: [twitter, facebook, linkedin]
  favicon: images/favicon.png
  twitter-card: true
  open-graph: true
  publisher: "Ipea - Instituto de Pesquisa Econômica Aplicada"
  publisher-place: "Brasilia - DF, Brazil"
  google-analytics:
    tracking-id: "G-YVERJQF9PJ"
    anonymize-ip: true


  chapters:
    - index.qmd
    - part: s1_intro.qmd
      chapters:
        - 1_conceito.qmd
        - 2_indicadores.qmd
    - part: s2_calculo.qmd
      chapters:
        - 3_calculando_acesso.qmd
    - part: s3_dados_tp.qmd
      chapters:
        - 4_dados_gtfs.qmd
        - 5_gtfstools.qmd
    - part: s4_avaliacao_impacto.qmd
      chapters:
        - 6_cenarios_transporte.qmd
    - part: s5_dados_aop.qmd
      chapters:
        - 7_aopdata_populacao.qmd
        - 8_aopdata_uso_solo.qmd
        - 9_aopdata_acessibilidade.qmd
    - references.qmd

  page-navigation: true
  page-footer: 
    border: false
    left: "Copyright 2023, Ipea - Instituto de Pesquisa Econômica Aplicada" 
    right: 
      - icon: github
        href: https://github.com/ipeaGIT/intro_access_book

  sidebar:
    tools:
      - icon: download
        href: https://repositorio.ipea.gov.br/bitstream/11058/12264/51/Introducao_a_acessibilidade_urbana_selo.pdf
        text: "Download PDF"

bibliography: references.bib

fig-dpi: 300

editor_options:
  markdown:
    wrap: 80
    canonical: true

theme:
  light: cosmo
  dark: superhero
  
crossref:
  fig-title: Figura
  fig-prefix: Figura
  tbl-title: Tabela
  tbl-prefix: Tabela
  sec-prefix: Seção

citation:
  type: book
  title: "Introdução à acessibilidade urbana: um guia prático em R"
  author:
    - Rafael H. M. Pereira
    - Daniel Herszenhut
  url: "https://ipeagit.github.io/intro_access_book/pt"
  pdf-url: "https://repositorio.ipea.gov.br/bitstream/11058/12264/51/Introducao_a_acessibilidade_urbana_selo.pdf"
  edition: 1
  issued: 2023
  isbn: "978-65-5635-054-7"
  doi: "http://dx.doi.org/10.38116/9786556350547"

google-scholar: true
